# Generated by Django 2.2.6 on 2019-11-11 01:35

from django.db import migrations, models
import harmony_checker.voiceleading


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(harmony_checker.voiceleading.get_num_parts, 'Number of Parts'), (harmony_checker.voiceleading.get_missing_notes, 'Missing Notes'), (harmony_checker.voiceleading.get_parts_out_of_range, 'Parts out of Range'), (harmony_checker.voiceleading.get_doubled_leading_tones, 'Doubled Leading Tones'), (harmony_checker.voiceleading.get_omitted_thirds, 'Omitted Thirds'), (harmony_checker.voiceleading.get_overspacing, 'Overspaced Chords'), (harmony_checker.voiceleading.get_melodic_aug_2, 'Melodic Augmented 2nd'), (harmony_checker.voiceleading.get_parallel_fifths, 'Parallel Fifths'), (harmony_checker.voiceleading.get_d5_to_p5, 'Diminished 5th to Perfect 5th'), (harmony_checker.voiceleading.get_hidden_fifths, 'Hidden Fifths'), (harmony_checker.voiceleading.get_hidden_octaves, 'Hidden Octaves'), (harmony_checker.voiceleading.get_crossed_voices, 'Crossed Voices')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FileField(upload_to='uploads/')),
                ('tests', models.ManyToManyField(to='harmony_checker.Tests')),
            ],
        ),
    ]
