# Generated by Django 2.2.6 on 2019-11-16 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        ('harmony_checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony_checker.Score', verbose_name='related score')),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony_checker.Test', verbose_name='related test')),
            ],
        ),
    ]
