# Generated by Django 2.2.6 on 2019-11-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0005_auto_20191116_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='result',
        ),
        migrations.RemoveField(
            model_name='test',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='tests',
            field=models.ManyToManyField(to='harmony_checker.Test'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(null=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony_checker.Score')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony_checker.Test')),
            ],
        ),
    ]
