# Generated by Django 2.2.6 on 2019-11-18 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harmony_checker', '0007_auto_20191117_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='checked_score',
            field=models.FileField(null=True, upload_to='checked/'),
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
