# Generated by Django 2.2.6 on 2019-12-29 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0008_auto_20191117_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Uploaded'),
            preserve_default=False,
        ),
    ]
