# Generated by Django 2.2.6 on 2019-12-30 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0009_score_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='function',
            field=models.CharField(default='func', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Uploaded'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
