# Generated by Django 2.2.6 on 2019-12-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0010_auto_20191230_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='function',
            field=models.CharField(default=models.CharField(max_length=50, unique=True), max_length=50, unique=True),
        ),
    ]
