# Generated by Django 2.2.6 on 2019-12-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0012_auto_20191230_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='function',
        ),
    ]
