# Generated by Django 2.2.6 on 2019-12-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0014_auto_20191230_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
