# Generated by Django 2.2.6 on 2019-12-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0016_test_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='func',
            field=models.CharField(default=models.CharField(max_length=50, unique=True), max_length=50),
        ),
    ]
