# Generated by Django 2.2.6 on 2019-12-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0018_auto_20191230_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='func',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
