# Generated by Django 2.2.6 on 2019-12-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0019_auto_20191230_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='checked_score_display_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='score_display_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
