# Generated by Django 2.2.6 on 2019-12-31 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0020_auto_20191230_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
