# Generated by Django 2.2.6 on 2019-12-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0021_auto_20191231_0859'),
    ]

    operations = [
    ]
