# Generated by Django 2.2.6 on 2020-02-13 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('harmony_checker', '0022_auto_20191231_0917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='MusicalTest',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='test',
            new_name='musical_test',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='tests',
            new_name='musical_tests',
        ),
        migrations.AlterField(
            model_name='score',
            name='score_display_name',
            field=models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False), max_length=50),
        ),
    ]

    atomic = False
